spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/flow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: '!jelly0403'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect


app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3002}

logging:
  level:
    com.basic.template.backend_template: INFO
    root: INFO