spring:
  application:
    name: backend-template

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8080}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/backend-template.log
    max-size: 10MB
    max-history: 30
  level:
    org.springframework.boot.web.embedded.tomcat: INFO  # 이 줄 추가
    org.springframework.boot: INFO                       # 이 줄 추가
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
