spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/flow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: '!jelly0403'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 앱 설정
app:
  upload:
    path: ${UPLOAD_PATH:/d/source/flow/data}

logging:
  level:
    flow: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO