spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://mariadb:3306/flow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:flow_user}
    password: ${DB_PASSWORD:!jelly0403}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: /flow/temp


app:
  upload:
    path: /flow/data

logging:
  level:
    com.basic.template.backend_template: INFO
    org.springframework.security: WARN
    root: INFO
  file:
    name: /flow/logs/backend-template.log