spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://mariadb:3306/flow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:!jelly0403}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect


app:
  frontend:
    url: ${FRONTEND_URL:http://frontend:3000}

logging:
  level:
    com.basic.template.backend_template: INFO
    org.springframework.security: WARN
    root: WARN